:recycle: Changed from bash to sh whereever possible in custom scripts

diff --git a/Scripts/colors/print-colors b/Scripts/colors/print-colors
--- a/Scripts/colors/print-colors
+++ b/Scripts/colors/print-colors
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 
-help_message="""\
+help_message="\
 usage: print-colors [options]
   options:
     -h, --help                   Shows this help message
     -b, --bit                    Specify the type of the colors (8-bit or 10-bit)
-"""
+"
 
 print10BitColors() {
-  awk -v term_cols="${width:-$(tput cols || echo 80)}" 'BEGIN{
+	awk -v term_cols="${width:-$(tput cols || echo 80)}" 'BEGIN{
       s="/\\";
       for (colnum = 0; colnum<term_cols; colnum++) {
           r = 255-(colnum*255/term_cols);
@@ -24,42 +24,42 @@ print10BitColors() {
 }
 
 print8BitColors() {
-  for i in {0..255} ; do
-      printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
-      if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
-          printf "\n";
-      fi
-  done
+	for i in {0..255}; do
+		printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
+		if ((i == 15)) || ((i > 15)) && (((i - 15) % 6 == 0)); then
+			printf "\n"
+		fi
+	done
 }
 
 while test $# -gt 0; do
-  case "$1" in
-    -h|--help)
-      echo "$help_message"
-      exit 0
-      ;;
-    -b|--bit)
-      shift
-      if test $# -gt 0; then
-        if [ $1 == "8" ]; then
-          print8BitColors
-        elif [ $1 == "10" ]; then
-          print10BitColors
-        else
-          echo "Invalid type specified!" && exit 1
-        fi
-        exit 0
-      else
-        echo "No type specified!"
-        exit 1
-      fi
-      shift
-      ;;
-    *)
-      echo "$help_message"
-      exit 1
-      ;;
-  esac
+	case "$1" in
+		-h | --help)
+			echo "$help_message"
+			exit 0
+			;;
+		-b | --bit)
+			shift
+			if test $# -gt 0; then
+				if [ "$1" == "8" ]; then
+					print8BitColors
+				elif [ "$1" == "10" ]; then
+					print10BitColors
+				else
+					echo "Invalid type specified!" && exit 1
+				fi
+				exit 0
+			else
+				echo "No type specified!"
+				exit 1
+			fi
+			shift
+			;;
+		*)
+			echo "$help_message"
+			exit 1
+			;;
+	esac
 done
 
 echo "$help_message" && exit 1
