:recycle: Changed all remaining scripts to be posix compliant

diff --git a/Scripts/install/install-nvim b/Scripts/install/install-nvim
--- a/Scripts/install/install-nvim
+++ b/Scripts/install/install-nvim
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 check_for_command() {
-  if command -v "$1" &> /dev/null; then
-    echo "Found '$1'! Continuing installation"
-  else
-    echo "'$1' not found! Please install '$1' first!" && exit 1
-  fi
+	if command -v "$1" >/dev/null 2>&1; then
+		echo "Found '$1'! Continuing installation"
+	else
+		echo "'$1' not found! Please install '$1' first!" && exit 1
+	fi
 }
 
 # Check if nvim is installed
@@ -26,4 +26,3 @@ echo "Installed pynvim!"
 echo "Installing neovim (node package) using npm..."
 npm i -g "neovim"
 echo "Installed neovim!"
-
